apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /argo-cd/$2
{{- if .Values.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.tls.ClusterIssuer }}
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # If you encounter a redirect loop or are getting a 307 response code
    # then you need to force the nginx ingress to connect to the backend using HTTPS.
    #
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
{{- end }}
spec:
  rules:
  - http:
      paths:
        - path: /argo-cd(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port:
                number: 443
{{- if .Values.tls.enabled }}
    host: {{ .Values.hosts }}
  tls:
  - hosts:
    - {{ .Values.hosts }}
    secretName: argocd-secret # do not change, this is provided by Argo CD
{{- end }}